version: '3.3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/home/app
    command: >
      /bin/bash -c '[[ "${ENVIRONMENT}" == "local" ]] && py manage.py runserver 0.0.0.0:8000 || /usr/bin/supervisord'
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
